name: bobrossify
description: Turn anything into a Bob Ross masterpiece.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker:
  firebase_storage:
  cloud_firestore:
  uuid: 
  transparent_image:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true